In [195]:
%matplotlib notebook
import os
import plotly.plotly as py
import plotly
import pandas as pd
import plotly.graph_objs as go
from imp import reload
import numpy as np
import cranium
from scipy.optimize import minimize
from scipy.optimize import minimize_scalar
import matplotlib.pyplot as plt
import scipy

#plotly.tools.set_credentials_file(username='msschwartz21', api_key='OrM0hMDBvseeT6SCjxNb')
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [51]:
reload(cranium)

<module 'cranium' from 'c:\\users\\zfishlab\\code\\craniumpy\\cranium\\__init__.py'>

In [59]:
dirs = ["C:\\Users\\zfishlab\\Desktop\\zrf1wt13umyot21um\\wt\\AT2",
	"C:\\Users\\zfishlab\\Desktop\\zrf1wt13umyot21um\\wt\\ZRF1",
	"C:\\Users\\zfishlab\\Desktop\\zrf1wt13umyot21um\\yot\\AT",
	"C:\\Users\\zfishlab\\Desktop\\zrf1wt13umyot21um\\yot\\ZRF1"]

In [152]:
%%time
wtatdfs = read_csvs(dirs[1])


Wall time: 2.24 s


In [148]:
%%time
#Yot dfs
yotatdfs = read_csvs(dirs[2])
yhms,yxbin,yybin = create_avg_hm(yotatdfs,'theta','ac',15,50)
yavghm = np.mean(yhms,axis=0)
ycmin = np.min(yavghm)
ycmax = np.max(yavghm)

[ 0.   0.2  0.4  0.7  0.9  1.1  1.3  1.6  1.8  2.   2.2  2.5  2.7  2.9  3.1]
[-138.4 -131.9 -125.5 -119.  -112.6 -106.1  -99.7  -93.3  -86.8  -80.4
  -73.9  -67.5  -61.   -54.6  -48.1  -41.7  -35.3  -28.8  -22.4  -15.9
   -9.5   -3.     3.4    9.8   16.3   22.7   29.2   35.6   42.1   48.5
   54.9   61.4   67.8   74.3   80.7   87.2   93.6  100.   106.5  112.9
  119.4  125.8  132.3  138.7  145.2  151.6  158.   164.5  170.9  177.4]
Wall time: 1.05 s


In [150]:
print(cmin,cmax)
print(ycmin,ycmax)

0.0 2253.23529412
0.0 196.083333333


In [153]:
%%time
acbin = np.linspace(minac,maxac,num=80)
tbin = np.linspace(mint,maxt,num=15)
hms,xbin,ybin = create_avg_hm(wtatdfs,'theta','ac',15,50)
avghm = np.mean(hms,axis=0)
cmin = np.min(avghm)
cmax = np.max(avghm)
avghm.shape

[ 0.   0.2  0.4  0.7  0.9  1.1  1.3  1.6  1.8  2.   2.2  2.5  2.7  2.9  3.1]
[-200.8 -192.1 -183.3 -174.6 -165.8 -157.1 -148.3 -139.6 -130.8 -122.1
 -113.3 -104.6  -95.8  -87.1  -78.3  -69.6  -60.8  -52.   -43.3  -34.5
  -25.8  -17.    -8.3    0.5    9.2   18.    26.7   35.5   44.2   53.
   61.7   70.5   79.2   88.    96.7  105.5  114.2  123.   131.7  140.5
  149.2  158.   166.7  175.5  184.2  193.   201.7  210.5  219.2  228. ]
Wall time: 317 ms


# Need to change binning so that it covers the same range for all samples

In [157]:
def create_hm_plot(filedir):
    dfs = read_csvs(filedir)
    hms,xbin,ybin = create_avg_hm(dfs,'theta','ac',15,50)
    avghm = np.mean(hms,axis=0)
    
    trace = go.Heatmap(z=avghm,
                      x=ybin,
                      y=xbin,
                      colorscale='Viridis',
                    )
    return(trace)

In [160]:
wtat = create_hm_plot(dirs[0])
wtzrf1 = create_hm_plot(dirs[1])
yat = create_hm_plot(dirs[2])
yzrf1 = create_hm_plot(dirs[3])

[ 0.   0.2  0.4  0.7  0.9  1.1  1.3  1.6  1.8  2.   2.2  2.5  2.7  2.9  3.1]
[ -1.36200000e+02  -1.28600000e+02  -1.21100000e+02  -1.13500000e+02
  -1.05900000e+02  -9.84000000e+01  -9.08000000e+01  -8.32000000e+01
  -7.57000000e+01  -6.81000000e+01  -6.06000000e+01  -5.30000000e+01
  -4.54000000e+01  -3.79000000e+01  -3.03000000e+01  -2.27000000e+01
  -1.52000000e+01  -7.60000000e+00  -1.00000000e-01   7.50000000e+00
   1.51000000e+01   2.26000000e+01   3.02000000e+01   3.78000000e+01
   4.53000000e+01   5.29000000e+01   6.04000000e+01   6.80000000e+01
   7.56000000e+01   8.31000000e+01   9.07000000e+01   9.83000000e+01
   1.05800000e+02   1.13400000e+02   1.20900000e+02   1.28500000e+02
   1.36100000e+02   1.43600000e+02   1.51200000e+02   1.58800000e+02
   1.66300000e+02   1.73900000e+02   1.81400000e+02   1.89000000e+02
   1.96600000e+02   2.04100000e+02   2.11700000e+02   2.19300000e+02
   2.26800000e+02   2.34400000e+02]


C:\Users\zfishlab\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\function_base.py:968: RuntimeWarning:

invalid value encountered in greater_equal



[ 0.   0.2  0.4  0.7  0.9  1.1  1.3  1.6  1.8  2.   2.2  2.5  2.7  2.9  3.1]
[-200.8 -192.1 -183.3 -174.6 -165.8 -157.1 -148.3 -139.6 -130.8 -122.1
 -113.3 -104.6  -95.8  -87.1  -78.3  -69.6  -60.8  -52.   -43.3  -34.5
  -25.8  -17.    -8.3    0.5    9.2   18.    26.7   35.5   44.2   53.
   61.7   70.5   79.2   88.    96.7  105.5  114.2  123.   131.7  140.5
  149.2  158.   166.7  175.5  184.2  193.   201.7  210.5  219.2  228. ]
[ 0.   0.2  0.4  0.7  0.9  1.1  1.3  1.6  1.8  2.   2.2  2.5  2.7  2.9  3.1]
[-138.4 -131.9 -125.5 -119.  -112.6 -106.1  -99.7  -93.3  -86.8  -80.4
  -73.9  -67.5  -61.   -54.6  -48.1  -41.7  -35.3  -28.8  -22.4  -15.9
   -9.5   -3.     3.4    9.8   16.3   22.7   29.2   35.6   42.1   48.5
   54.9   61.4   67.8   74.3   80.7   87.2   93.6  100.   106.5  112.9
  119.4  125.8  132.3  138.7  145.2  151.6  158.   164.5  170.9  177.4]
[ 0.   0.2  0.4  0.7  0.9  1.1  1.3  1.6  1.8  2.   2.2  2.5  2.7  2.9  3.1]
[-167.1 -160.3 -153.5 -146.7 -139.9 -133.2 -126.4 -119.6 -

In [161]:
Lmax=[]
for trace in [wtat,wtzrf1,yat,yzrf1]:
    Lmax.append(np.max(trace['z']))
cmax = np.max(Lmax)
cmax

2253.2352941176468

In [166]:
Lmax

[2253.2352941176468,
 450.29411764705884,
 196.08333333333334,
 184.58333333333334]

In [187]:
for trace in [wtat,yat]:
    trace['zmin'] = 0
    trace['zmax'] = 2253
    trace['colorscale'] = 'Electric'

In [185]:
for trace in [wtzrf1,yzrf1]:
    trace['zmin'] = 0
    trace['zmax'] = 450
    trace['colorscale'] = 'Hot' #hot

In [203]:
xaxis = dict(
    title = 'Position along the commissure',
    range = [-200,200]
)
yaxis = dict(
    title = 'Angle around the commissure (radians)',
)
layout = dict(
    xaxis = xaxis,
    yaxis = yaxis
)

In [207]:
layout['xaxis']['range'] = [-160,160]
fig = go.Figure(data=[yzrf1],layout=layout)
iplot(fig,filename='final_yotzrf1_hm_theta')

In [208]:
layout['xaxis']['range'] = [-200,200]
fig = go.Figure(data=[wtzrf1],layout=layout)
iplot(fig,filename='final_wtzrf1_hm_theta')

In [212]:
layout['xaxis']['range'] = [-100,100]
fig = go.Figure(data=[yat],layout=layout)
iplot(fig,filename='final_ywt_hm_theta')

In [211]:
layout['xaxis']['range'] = [-100,100]
fig = go.Figure(data=[wtat],layout=layout)
iplot(fig,filename='final_atwt_hm_theta')

In [56]:
def read_csvs(filedir):
    files = os.listdir(filedir)
    dfs = []
    for file in files:
        if 'Probabilities' in file and 'csv' in file:
            df = pd.read_csv(os.path.join(filedir,file))
            dfs.append(df)
    return(dfs)

In [57]:
def find_range(dfs,key):
    Lmin,Lmax = [],[]
    for df in dfs:
        Lmin.append(np.min(df[key]))
        Lmax.append(np.max(df[key]))
        
    minv = np.min(Lmin)
    maxv = np.max(Lmax)
    return(minv,maxv)

In [143]:
def create_avg_hm(dfs,xkey,ykey,xnum,ynum):
    xmin,xmax = find_range(dfs,xkey)
    xbins = np.linspace(xmin,xmax,num=xnum)
    ymin,ymax = find_range(dfs,ykey)
    ybins = np.linspace(ymin,ymax,num=ynum)
    print(np.around(xbins,decimals=1))
    print(np.around(ybins,decimals=1))
    
    Lhm = []
    for i,df in enumerate(dfs):
        hm = np.histogram2d(df[xkey],df[ykey],bins=[xbins,ybins])
        if i == 0:
            hms = np.zeros((len(dfs),hm[0].shape[0],hm[0].shape[1]))
            hms[i] = hm[0]
        else:
            hms[i] = hm[0]
        Lhm.append(hm)
    return(hms,hm[1],hm[2])

# 3D plots

# Tiny histograms

In [ ]:
for 